### ISSUE TITLE
Can't get option chain for stock 

### ISSUE THREAD

**Issue by ratan00** [StreamAlpha/pynse#6]
symbol name - COROMANDEL it says its not a valid symbol, is there some rule or something that i am missing ?

Traceback (most recent call last):

  File "/tmp/ipykernel_22279/1793251367.py", line 1, in <module>
    nse.option_chain('COROMANDEL')

  File "/home/spidy/Documents/pynse/core.py", line 584, in option_chain
    symbol = self.__validate_symbol(

  File "/home/spidy/Documents/pynse/core.py", line 244, in __validate_symbol
    raise ValueError('not a vaild symbol')

ValueError: not a vaild symbol

**Comment by StreamAlpha** [comment]
update symbols list once
https://github.com/StreamAlpha/pynse#update-symbol-lists

**Comment by ratan00** [comment]
yeah i did tried it before it didn't work atm but now it did when i retried so thanks, for this nice library too
